### ISSUE TITLE
Cannot change the back color in Basic-Anking

### ISSUE THREAD

**Issue by Farinata** [AnKing-VIP/AnKing-Note-Types#123]
This is the third time I am reporting this Bug, still no fix.
The "back" color cannot be changed in the Basic-Anking note type.
Although it is set to blue by default, only appears white or black (depends on night mode).
Even when you change blue to something else nothing happens.
Note that it is working fine for the other fields (front, personal notes, missed questions)

**Comment by AnKingMed** [comment]
I apologize. 

Try changing `.cloze` or `#extra` [here](https://github.com/AnKing-Memberships/AnKing-Note-Types/blob/3ad7f8c215af405fde3cd8825aef391e4a7f7174/src/notetypes/Basic-AnKing/Styling.css#L82) to `#back`

@RisingOrange what would be the best way to add support for this via the add-on? Should we change the id to `#back` or just wrap the back section in `#extra` instead of `#back` for ease of making it work with the add-on since this is a basic note type?

**Comment by AnKingMed** [comment]
@RisingOrange any thoughts on this? I can actually make the update

**Comment by RisingOrange** [comment]
Sorry, is this about the text colour on the back of the card?

**Comment by AnKingMed** [comment]
It's about the color of the back of the card. It's not currently customizable because the addon only lets you customize the cloze and extra color

**Comment by abdnh** [comment]
I modified Basic-Anking to use `#back` instead of `.cloze` and added options to the add-on to customize the color.
