### ISSUE TITLE
Make one by one clozes green from the start to signify note type

### ISSUE THREAD

**Issue by AnKingMed** [AnKing-VIP/AnKing-Note-Types#149]
When the one by one clozes have a hint in them, they turn green on card flip. Can we make it so the clozes are green from the start so that users know it's a cloze one by one to begin with? Then it wouldn't matter if we turn it green if there's hints or not

**Comment by AnKingMed** [comment]
@abdnh can you look into this? I'm hoping it's a simple change

**Comment by AnKingMed** [comment]
@abdnh are you planning to work on this in the near future? If so, I'll wait for this before pushing the new update

**Comment by abdnh** [comment]
Will look into it today.

**Comment by AnKingMed** [comment]
@abdnh I encountered a very odd bug this morning. When I reviewed a cloze one by one on iOS, all clozes after it were green unless I edited a card, then it would change back to blue until I ran into another cloze one by one. Any idea what would cause this? Should I report it on forums.ankiweb.net?

**Comment by abdnh** [comment]
Should be fixed now. I just used the wrong approach. I made it add a "one-by-one" class to the root "qa" element thinking Anki will clear it for each card but turned out this is not the case. The class is now added to each cloze element, so one-by-one clozes have the "cloze one-by-one" classes and can be styled using ".cloze.one-by-one".
